// Deterministic generation of src/styles/tokens.css from the token JSON files and figma-state.json.
// The file is a build product: edit the sources and regenerate, never edit it by hand.

import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { aliasCycleProblems } from "./alias-cycles.mjs";
import { isValidCssName } from "./css-name.mjs";
import { modeScopeProblems } from "./mode-scopes.mjs";
import { createFloatResolver, floatAliasProblems, isLocalAliasVariable, serializationProblems, serializeNumber } from "./serialization.mjs";

export const TOKENS_CSS_PATH = "src/styles/tokens.css";
export const GENERATOR_COMMAND = "node .agents/skills/create-ds-from-figma/scripts/generate-tokens-css.mjs";
export const TOKENS_CSS_HEADER =
  `/* Generated by ${GENERATOR_COMMAND} from design-system/tokens/*.json and figma-state.json. Do not edit by hand; regenerate it. */`;

const isObject = (value) => value !== null && typeof value === "object" && !Array.isArray(value);
const byCodePoint = (left, right) => (left < right ? -1 : left > right ? 1 : 0);

// A CSS string token for a STRING variable: double quotes, backslash and control characters escaped.
export function cssString(value) {
  const escaped = [...String(value)].map((character) => {
    const code = character.codePointAt(0);
    if (character === "\\") return "\\\\";
    if (character === '"') return '\\"';
    if (code < 32 || code === 127) return `\\${code.toString(16)} `;
    return character;
  }).join("");
  return `"${escaped}"`;
}

/**
 * collections  [{ file, record, data }]  token JSON plus its figma-state.json collection record
 * externals    [{ id, cssName, type, value }]  resolved snapshots recorded in the component sheets
 * Returns { css, errors, warnings }. Nothing is guessed: a FLOAT without a serialization decision is not written.
 */
export function renderTokensCss({ collections, externals = [] }) {
  const errors = [];
  const warnings = [];
  const sorted = [...collections].sort((a, b) => byCodePoint(a.file, b.file));
  const variables = new Map();
  const decisions = new Map();
  const cssNameOwners = new Map();
  for (const { file, record, data } of sorted) {
    for (const variable of Object.values(data.variables ?? {})) {
      if (!isObject(variable)) continue;
      if (!isValidCssName(variable.cssName)) {
        errors.push(`tokens/${file}: variable ${variable.id} needs a valid cssName`);
        continue;
      }
      if (variables.has(variable.id)) errors.push(`tokens/${file}: duplicate variable id ${variable.id}`);
      else variables.set(variable.id, { ...variable, file });
      if (cssNameOwners.has(variable.cssName)) errors.push(`tokens/${file}: duplicate cssName ${variable.cssName}`);
      else cssNameOwners.set(variable.cssName, variable.id);
    }
    const scopes = modeScopeProblems(record, data, `tokens/${file}`);
    errors.push(...scopes.errors);
    warnings.push(...scopes.warnings);
    const checked = serializationProblems(record, data, `tokens/${file}`);
    errors.push(...checked.errors);
    for (const [id, css] of checked.decisions) decisions.set(id, css);
  }
  const cycles = aliasCycleProblems(sorted);
  errors.push(...cycles.errors);
  warnings.push(...cycles.warnings);
  const externalById = new Map();
  for (const variable of externals) {
    if (!isObject(variable) || typeof variable.id !== "string" || !variable.id || !isValidCssName(variable.cssName)) {
      errors.push("external variable snapshot needs id and a valid cssName");
      continue;
    }
    const previous = externalById.get(variable.id);
    if (previous && (previous.cssName !== variable.cssName || previous.type !== variable.type || previous.value !== variable.value)) {
      errors.push(`conflicting snapshots for variable ${variable.id}`);
    } else if (!previous) {
      externalById.set(variable.id, variable);
    }
    if (variables.has(variable.id)) errors.push(`external variable ${variable.id} duplicates a local variable id`);
    const owner = cssNameOwners.get(variable.cssName);
    if (owner && owner !== variable.id) errors.push(`external cssName ${variable.cssName} conflicts with variable ${owner}`);
    else cssNameOwners.set(variable.cssName, variable.id);
  }
  if (errors.length) return { css: "", errors, warnings };
  const resolveFloat = createFloatResolver({ variables, decisions });
  errors.push(...floatAliasProblems({ variables, resolveFloat }));

  const direct = (type, value, variable) => {
    if (type === "COLOR") return typeof value === "string" ? value : undefined;
    if (type === "STRING") return typeof value === "string" ? cssString(value) : undefined;
    if (type === "BOOLEAN") return typeof value === "boolean" ? String(value) : undefined;
    if (type === "FLOAT") {
      const resolved = resolveFloat(variable.id);
      if (resolved.status === "conflict") errors.push(`tokens/${variable.file} ${variable.cssName}: ${resolved.message}`);
      return resolved.status === "decided" ? serializeNumber(value, resolved.css) : undefined;
    }
    return undefined;
  };
  const emit = (variable, raw) => {
    if (isObject(raw) && raw.source === "local") {
      const target = variables.get(raw.targetVariableId);
      if (!target) {
        errors.push(`tokens/${variable.file} ${variable.cssName}: local alias target ${raw.targetVariableId} not found`);
        return undefined;
      }
      if (variable.type === "FLOAT") {
        const resolved = resolveFloat(variable.id);
        if (resolved.status === "conflict") errors.push(`tokens/${variable.file} ${variable.cssName}: ${resolved.message}`);
        if (resolved.status !== "decided") return undefined;
      }
      return `var(${target.cssName})`;
    }
    return direct(variable.type, isObject(raw) ? raw.value : raw, variable);
  };

  const lines = [TOKENS_CSS_HEADER, ":root {"];
  const pending = [];
  for (const { file, data } of sorted) {
    lines.push(`  /* ${file} */`);
    for (const variable of Object.values(data.variables ?? {})) {
      if (!isObject(variable)) continue;
      const value = emit({ ...variable, file }, variable.valuesByMode?.[data.defaultMode]);
      if (value === undefined) {
        if (variable.type === "FLOAT") pending.push(`${file}: ${variable.cssName}`);
        continue;
      }
      lines.push(`  ${variable.cssName}: ${value};`);
    }
  }
  const external = [];
  for (const variable of [...externalById.values()].sort((a, b) => byCodePoint(a.cssName, b.cssName))) {
    if (variable.type === "FLOAT") {
      pending.push(`external: ${variable.cssName}`);
      continue;
    }
    const value = direct(variable.type, variable.value, { ...variable, file: "external" });
    if (value !== undefined) external.push(`  ${variable.cssName}: ${value};`);
  }
  if (external.length) lines.push("  /* external variables (resolved snapshots of another library) */", ...external);
  lines.push("}");

  for (const { file, record, data } of sorted) {
    const scopes = isObject(record?.modeScopes) ? record.modeScopes : {};
    const blockFor = (mode, indent) => {
      const body = [];
      for (const variable of Object.values(data.variables ?? {})) {
        if (!isObject(variable)) continue;
        const entry = { ...variable, file };
        const wanted = emit(entry, variable.valuesByMode?.[mode]);
        if (wanted !== undefined && wanted !== emit(entry, variable.valuesByMode?.[data.defaultMode])) {
          body.push(`${indent}  ${variable.cssName}: ${wanted};`);
        }
      }
      return body;
    };
    const mapped = data.modes.filter((mode) => mode !== data.defaultMode && isObject(scopes[mode]));
    for (const mode of mapped.filter((name) => scopes[name].kind === "selector")) {
      lines.push(`${scopes[mode].value} {`, ...blockFor(mode, ""), "}");
    }
    for (const mode of mapped.filter((name) => scopes[name].kind === "media").sort((a, b) => scopes[a].order - scopes[b].order)) {
      lines.push(`@media ${scopes[mode].query} {`, "  :root {", ...blockFor(mode, "  "), "  }", "}");
    }
  }
  if (pending.length) {
    warnings.push(`${pending.length} FLOAT variable(s) have no serialization decision and are not written (NOT VERIFIED): ${pending.slice(0, 3).join(", ")}${pending.length > 3 ? ", ..." : ""}`);
  }
  return { css: `${lines.join("\n")}\n`, errors, warnings };
}

const readJson = (file) => {
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch (error) {
    throw new Error(`${file}: ${error.message}`);
  }
};

/** Reads the sources from disk and renders the stylesheet. Returns { css, errors, warnings }. */
export function generateTokensCss(root) {
  const errors = [];
  let state;
  let map;
  try {
    state = readJson(path.join(root, "design-system/relationships/figma-state.json"));
    map = existsSync(path.join(root, "design-system/relationships/figma-code-map.json"))
      ? readJson(path.join(root, "design-system/relationships/figma-code-map.json")) : {};
  } catch (error) {
    return { css: "", errors: [error.message], warnings: [] };
  }
  const stateCollections = isObject(state.collections) ? state.collections : {};
  const tokensDir = path.join(root, "design-system/tokens");
  const collections = [];
  const claimed = new Set();
  for (const file of existsSync(tokensDir) ? readdirSync(tokensDir).filter((item) => /\.json$/i.test(item)).sort(byCodePoint) : []) {
    let data;
    try {
      data = readJson(path.join(tokensDir, file));
    } catch (error) {
      errors.push(error.message);
      continue;
    }
    const record = isObject(data) ? stateCollections[data.id] : undefined;
    if (!isObject(data) || !isObject(data.variables) || !Array.isArray(data.modes) || !isObject(record)) {
      errors.push(`tokens/${file}: not a valid collection registered in figma-state.json`);
      continue;
    }
    claimed.add(data.id);
    collections.push({ file, record, data });
  }
  for (const id of Object.keys(stateCollections)) {
    if (!claimed.has(id)) errors.push(`figma-state.json collection ${id}: token JSON is missing`);
  }
  const externals = [];
  const mappedMetadata = new Set();
  for (const [key, entry] of Object.entries(isObject(map) ? map : {}).filter(([key]) => !key.startsWith("_"))) {
    const metadataFile = entry?.designSystem?.metadata;
    if (typeof metadataFile !== "string" || path.isAbsolute(metadataFile) || metadataFile.split(/[\\/]/).includes("..")) {
      errors.push(`map ${key}: invalid metadata path`);
      continue;
    }
    const full = path.join(root, metadataFile);
    mappedMetadata.add(full);
    if (!existsSync(full)) {
      errors.push(`map ${key}: missing ${metadataFile}`);
      continue;
    }
    try {
      const externalVariables = readJson(full).externalVariables;
      if (!Array.isArray(externalVariables)) {
        errors.push(`${metadataFile}: externalVariables must be a list`);
      } else {
        externals.push(...externalVariables);
      }
    } catch (error) {
      errors.push(error.message);
    }
  }
  const componentsDir = path.join(root, "design-system/components");
  if (existsSync(componentsDir)) {
    for (const component of readdirSync(componentsDir, { withFileTypes: true }).filter((entry) => entry.isDirectory())) {
      const metadataFile = path.join(componentsDir, component.name, "metadata.json");
      if (!existsSync(metadataFile) || mappedMetadata.has(metadataFile)) continue;
      try {
        const metadata = readJson(metadataFile);
        if (!Array.isArray(metadata.externalVariables)) {
          errors.push(`${path.relative(root, metadataFile)}: externalVariables must be a list`);
        } else if (metadata.externalVariables.length) {
          errors.push(`${path.relative(root, metadataFile)} has externalVariables but is not registered in figma-code-map.json; register it before generating tokens.css`);
        }
      } catch (error) {
        errors.push(error.message);
      }
    }
  }
  if (errors.length) return { css: "", errors, warnings: [] };
  const rendered = renderTokensCss({ collections, externals });
  return rendered;
}

export function firstDifference(actual, expected) {
  const left = actual.split("\n");
  const right = expected.split("\n");
  for (let index = 0; index < Math.max(left.length, right.length); index += 1) {
    if (left[index] !== right[index]) return { line: index + 1, actual: left[index], expected: right[index] };
  }
  return null;
}
